# Generated by Django 4.1.6 on 2023-02-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechayHora', models.DateTimeField()),
                ('temperatura', models.CharField(max_length=200)),
                ('humedadRel', models.CharField(max_length=200)),
                ('humedadAbs', models.CharField(max_length=200)),
                ('velocidadVi', models.CharField(max_length=200)),
                ('direccionVi', models.CharField(max_length=200)),
                ('presionBaro', models.CharField(max_length=200)),
            ],
        ),
    ]
